### ISSUE TITLE
Deploy Processed Event serialisation fails

### ISSUE THREAD

**Issue by cnorburn** [casper-network/casper-java-sdk#146]
BufferEndCLValueDecodeException is thrown when processing an empty cl_type

{"WriteCLValue":
       {
              "cl_type":"U512",
              "bytes":"00",
              "parsed":"0"
       }

Failing test is in branch issues/120  EventBuilderTest buildDeployProcessedEvent

An example Event with an empty cl_type is also in the Casper documentation
https://docs.casperlabs.io/dapp-dev-guide/building-dapps/monitoring-events/

**Comment by oak** [comment]
Hi @cnorburn! I was taking a look and got this exception from your test:

```
Initializing with hexString: 00
Length of next number: 0

Error building POJO event for: data:{"DeployProcessed":{"deploy_hash":"fb81219f33aa58a2c2f50f7eea20c3065963f61bc3c74810729f10dc21981087","account":"01959d01aa68197e8cb91aa06bcc920f8d4a245dff60ea726bb89255349107a565","timestamp":"2022-07-26T14:37:15.150Z","ttl":"30m","dependencies":[],"block_hash":"5ae463abe56ebd37044600b90236d91fa93e3ff88d47f12a9c616d8b16ae9100","execution_result":{"Success":{"effect":{"operations":[],"transforms":[{"key":"hash-c5cbbfd90319b74de3e147e33c17d480ea782bafa37e2a08b7dda37d3713e036","transform":"Identity"},{"key":"account-hash-a6cdb6f049363f6ab119be0c961c36e4a3c09319589341dd861f405d9836fc67","transform":"Identity"},{"key":"account-hash-a6cdb6f049363f6ab119be0c961c36e4a3c09319589341dd861f405d9836fc67","transform":"Identity"},{"key":"hash-c5cbbfd90319b74de3e147e33c17d480ea782bafa37e2a08b7dda37d3713e036","transform":"Identity"},{"key":"hash-c5cbbfd90319b74de3e147e33c17d480ea782bafa37e2a08b7dda37d3713e036","transform":"Identity"},{"key":"hash-5ba9ce15ffc7429476de4e278d23362759e37cbdcafd1a8efb2f8bb475e8574e","transform":"Identity"},{"key":"hash-c5cbbfd90319b74de3e147e33c17d480ea782bafa37e2a08b7dda37d3713e036","transform":"Identity"},{"key":"hash-b8527fd6de4c547f7afef1427094846b68a8762e61cf118bb69ea7e78b9e82d4","transform":"Identity"},{"key":"hash-b8527fd6de4c547f7afef1427094846b68a8762e61cf118bb69ea7e78b9e82d4","transform":"Identity"},{"key":"hash-090f97f668d33884974255ba853c74fdd5fb187ba6e48c0ac652f00e81b2b67f","transform":"Identity"},{"key":"hash-b8527fd6de4c547f7afef1427094846b68a8762e61cf118bb69ea7e78b9e82d4","transform":"Identity"},{"key":"balance-0eeb2bd99ae07173be21a5fc86db7a2ea7fae0abdfb5e81350bf52f22a66ea80","transform":"Identity"},{"key":"balance-3fc748c8cad37d3c5b65d3cd53b189ec4f3da23475ce4d3dae02bc08e63b8329","transform":"Identity"},{"key":"balance-0eeb2bd99ae07173be21a5fc86db7a2ea7fae0abdfb5e81350bf52f22a66ea80","transform":{"WriteCLValue":{"cl_type":"U512","bytes":"0e001f0afa095bc138938d44c64d31","parsed":"999999999999999999999999900000000"}}},{"key":"balance-3fc748c8cad37d3c5b65d3cd53b189ec4f3da23475ce4d3dae02bc08e63b8329","transform":{"AddUInt512":"100000000"}},{"key":"hash-c5cbbfd90319b74de3e147e33c17d480ea782bafa37e2a08b7dda37d3713e036","transform":"Identity"},{"key":"account-hash-a6cdb6f049363f6ab119be0c961c36e4a3c09319589341dd861f405d9836fc67","transform":"Identity"},{"key":"account-hash-a6cdb6f049363f6ab119be0c961c36e4a3c09319589341dd861f405d9836fc67","transform":"Identity"},{"key":"hash-c5cbbfd90319b74de3e147e33c17d480ea782bafa37e2a08b7dda37d3713e036","transform":"Identity"},{"key":"hash-c5cbbfd90319b74de3e147e33c17d480ea782bafa37e2a08b7dda37d3713e036","transform":"Identity"},{"key":"hash-5ba9ce15ffc7429476de4e278d23362759e37cbdcafd1a8efb2f8bb475e8574e","transform":"Identity"},{"key":"hash-c5cbbfd90319b74de3e147e33c17d480ea782bafa37e2a08b7dda37d3713e036","transform":"Identity"},{"key":"hash-b8527fd6de4c547f7afef1427094846b68a8762e61cf118bb69ea7e78b9e82d4","transform":"Identity"},{"key":"hash-b8527fd6de4c547f7afef1427094846b68a8762e61cf118bb69ea7e78b9e82d4","transform":"Identity"},{"key":"hash-090f97f668d33884974255ba853c74fdd5fb187ba6e48c0ac652f00e81b2b67f","transform":"Identity"},{"key":"hash-b8527fd6de4c547f7afef1427094846b68a8762e61cf118bb69ea7e78b9e82d4","transform":"Identity"},{"key":"balance-0eeb2bd99ae07173be21a5fc86db7a2ea7fae0abdfb5e81350bf52f22a66ea80","transform":"Identity"},{"key":"balance-3fc748c8cad37d3c5b65d3cd53b189ec4f3da23475ce4d3dae02bc08e63b8329","transform":"Identity"},{"key":"balance-0eeb2bd99ae07173be21a5fc86db7a2ea7fae0abdfb5e81350bf52f22a66ea80","transform":{"WriteCLValue":{"cl_type":"U512","bytes":"0e001f0afa095bc138938d44c64d31","parsed":"999999999999999999999999900000000"}}},{"key":"balance-3fc748c8cad37d3c5b65d3cd53b189ec4f3da23475ce4d3dae02bc08e63b8329","transform":{"AddUInt512":"100000000"}},{"key":"hash-b8527fd6de4c547f7afef1427094846b68a8762e61cf118bb69ea7e78b9e82d4","transform":"Identity"},{"key":"hash-b8527fd6de4c547f7afef1427094846b68a8762e61cf118bb69ea7e78b9e82d4","transform":"Identity"},{"key":"hash-090f97f668d33884974255ba853c74fdd5fb187ba6e48c0ac652f00e81b2b67f","transform":"Identity"},{"key":"hash-b8527fd6de4c547f7afef1427094846b68a8762e61cf118bb69ea7e78b9e82d4","transform":"Identity"},{"key":"balance-0eeb2bd99ae07173be21a5fc86db7a2ea7fae0abdfb5e81350bf52f22a66ea80","transform":"Identity"},{"key":"balance-05f54a84872c75f7f05c8e8aaf9338ec848fa1a5b4f07202e371955c982f7f60","transform":"Identity"},{"key":"balance-0eeb2bd99ae07173be21a5fc86db7a2ea7fae0abdfb5e81350bf52f22a66ea80","transform":{"WriteCLValue":{"cl_type":"U512","bytes":"0e00260765095bc138938d44c64d31","parsed":"999999999999999999999997400000000"}}},{"key":"balance-05f54a84872c75f7f05c8e8aaf9338ec848fa1a5b4f07202e371955c982f7f60","transform":{"AddUInt512":"2500000000"}},{"key":"transfer-bae0cec10eb82aa81af18a31393ff5d5023e25ea7ed820e978b8407ccc22160d","transform":{"WriteTransfer":{"deploy_hash":"fb81219f33aa58a2c2f50f7eea20c3065963f61bc3c74810729f10dc21981087","from":"account-hash-59cbc880e6d1f7407f18c36393c33d47ae51d5a54258f94a837ff996bf25a34d","to":"account-hash-a6cdb6f049363f6ab119be0c961c36e4a3c09319589341dd861f405d9836fc67","source":"uref-0eeb2bd99ae07173be21a5fc86db7a2ea7fae0abdfb5e81350bf52f22a66ea80-007","target":"uref-05f54a84872c75f7f05c8e8aaf9338ec848fa1a5b4f07202e371955c982f7f60-004","amount":"2500000000","gas":"0","id":1}}},{"key":"deploy-fb81219f33aa58a2c2f50f7eea20c3065963f61bc3c74810729f10dc21981087","transform":{"WriteDeployInfo":{"deploy_hash":"fb81219f33aa58a2c2f50f7eea20c3065963f61bc3c74810729f10dc21981087","transfers":["transfer-bae0cec10eb82aa81af18a31393ff5d5023e25ea7ed820e978b8407ccc22160d"],"from":"account-hash-59cbc880e6d1f7407f18c36393c33d47ae51d5a54258f94a837ff996bf25a34d","source":"uref-0eeb2bd99ae07173be21a5fc86db7a2ea7fae0abdfb5e81350bf52f22a66ea80-007","gas":"100000000"}}},{"key":"hash-c5cbbfd90319b74de3e147e33c17d480ea782bafa37e2a08b7dda37d3713e036","transform":"Identity"},{"key":"hash-c5cbbfd90319b74de3e147e33c17d480ea782bafa37e2a08b7dda37d3713e036","transform":"Identity"},{"key":"hash-5ba9ce15ffc7429476de4e278d23362759e37cbdcafd1a8efb2f8bb475e8574e","transform":"Identity"},{"key":"hash-c5cbbfd90319b74de3e147e33c17d480ea782bafa37e2a08b7dda37d3713e036","transform":"Identity"},{"key":"balance-3fc748c8cad37d3c5b65d3cd53b189ec4f3da23475ce4d3dae02bc08e63b8329","transform":"Identity"},{"key":"hash-c5cbbfd90319b74de3e147e33c17d480ea782bafa37e2a08b7dda37d3713e036","transform":"Identity"},{"key":"hash-b8527fd6de4c547f7afef1427094846b68a8762e61cf118bb69ea7e78b9e82d4","transform":"Identity"},{"key":"hash-090f97f668d33884974255ba853c74fdd5fb187ba6e48c0ac652f00e81b2b67f","transform":"Identity"},{"key":"hash-b8527fd6de4c547f7afef1427094846b68a8762e61cf118bb69ea7e78b9e82d4","transform":"Identity"},{"key":"balance-3fc748c8cad37d3c5b65d3cd53b189ec4f3da23475ce4d3dae02bc08e63b8329","transform":"Identity"},{"key":"balance-8bd1ab925b4c91ea54b4aa6edadfd11d2be294cb64c59745258cb67e32aea67a","transform":"Identity"},{"key":"balance-3fc748c8cad37d3c5b65d3cd53b189ec4f3da23475ce4d3dae02bc08e63b8329","transform":{"WriteCLValue":{"cl_type":"U512","bytes":"00","parsed":"0"}}},{"key":"balance-8bd1ab925b4c91ea54b4aa6edadfd11d2be294cb64c59745258cb67e32aea67a","transform":{"AddUInt512":"100000000"}}]},"transfers":["transfer-bae0cec10eb82aa81af18a31393ff5d5023e25ea7ed820e978b8407ccc22160d"],"cost":"100000000"}}}}
com.casper.sdk.exception.CasperClientException: Error building POJO event for: data:{"DeployProcessed":{"deploy_hash":"fb81219f33aa58a2c2f50f7eea20c3065963f61bc3c74810729f10dc21981087","account":"01959d01aa68197e8cb91aa06bcc920f8d4a245dff60ea726bb89255349107a565","timestamp":"2022-07-26T14:37:15.150Z","ttl":"30m","dependencies":[],"block_hash":"5ae463abe56ebd37044600b90236d91fa93e3ff88d47f12a9c616d8b16ae9100","execution_result":{"Success":{"effect":{"operations":[],"transforms":[{"key":"hash-c5cbbfd90319b74de3e147e33c17d480ea782bafa37e2a08b7dda37d3713e036","transform":"Identity"},{"key":"account-hash-a6cdb6f049363f6ab119be0c961c36e4a3c09319589341dd861f405d9836fc67","transform":"Identity"},{"key":"account-hash-a6cdb6f049363f6ab119be0c961c36e4a3c09319589341dd861f405d9836fc67","transform":"Identity"},{"key":"hash-c5cbbfd90319b74de3e147e33c17d480ea782bafa37e2a08b7dda37d3713e036","transform":"Identity"},{"key":"hash-c5cbbfd90319b74de3e147e33c17d480ea782bafa37e2a08b7dda37d3713e036","transform":"Identity"},{"key":"hash-5ba9ce15ffc7429476de4e278d23362759e37cbdcafd1a8efb2f8bb475e8574e","transform":"Identity"},{"key":"hash-c5cbbfd90319b74de3e147e33c17d480ea782bafa37e2a08b7dda37d3713e036","transform":"Identity"},{"key":"hash-b8527fd6de4c547f7afef1427094846b68a8762e61cf118bb69ea7e78b9e82d4","transform":"Identity"},{"key":"hash-b8527fd6de4c547f7afef1427094846b68a8762e61cf118bb69ea7e78b9e82d4","transform":"Identity"},{"key":"hash-090f97f668d33884974255ba853c74fdd5fb187ba6e48c0ac652f00e81b2b67f","transform":"Identity"},{"key":"hash-b8527fd6de4c547f7afef1427094846b68a8762e61cf118bb69ea7e78b9e82d4","transform":"Identity"},{"key":"balance-0eeb2bd99ae07173be21a5fc86db7a2ea7fae0abdfb5e81350bf52f22a66ea80","transform":"Identity"},{"key":"balance-3fc748c8cad37d3c5b65d3cd53b189ec4f3da23475ce4d3dae02bc08e63b8329","transform":"Identity"},{"key":"balance-0eeb2bd99ae07173be21a5fc86db7a2ea7fae0abdfb5e81350bf52f22a66ea80","transform":{"WriteCLValue":{"cl_type":"U512","bytes":"0e001f0afa095bc138938d44c64d31","parsed":"999999999999999999999999900000000"}}},{"key":"balance-3fc748c8cad37d3c5b65d3cd53b189ec4f3da23475ce4d3dae02bc08e63b8329","transform":{"AddUInt512":"100000000"}},{"key":"hash-c5cbbfd90319b74de3e147e33c17d480ea782bafa37e2a08b7dda37d3713e036","transform":"Identity"},{"key":"account-hash-a6cdb6f049363f6ab119be0c961c36e4a3c09319589341dd861f405d9836fc67","transform":"Identity"},{"key":"account-hash-a6cdb6f049363f6ab119be0c961c36e4a3c09319589341dd861f405d9836fc67","transform":"Identity"},{"key":"hash-c5cbbfd90319b74de3e147e33c17d480ea782bafa37e2a08b7dda37d3713e036","transform":"Identity"},{"key":"hash-c5cbbfd90319b74de3e147e33c17d480ea782bafa37e2a08b7dda37d3713e036","transform":"Identity"},{"key":"hash-5ba9ce15ffc7429476de4e278d23362759e37cbdcafd1a8efb2f8bb475e8574e","transform":"Identity"},{"key":"hash-c5cbbfd90319b74de3e147e33c17d480ea782bafa37e2a08b7dda37d3713e036","transform":"Identity"},{"key":"hash-b8527fd6de4c547f7afef1427094846b68a8762e61cf118bb69ea7e78b9e82d4","transform":"Identity"},{"key":"hash-b8527fd6de4c547f7afef1427094846b68a8762e61cf118bb69ea7e78b9e82d4","transform":"Identity"},{"key":"hash-090f97f668d33884974255ba853c74fdd5fb187ba6e48c0ac652f00e81b2b67f","transform":"Identity"},{"key":"hash-b8527fd6de4c547f7afef1427094846b68a8762e61cf118bb69ea7e78b9e82d4","transform":"Identity"},{"key":"balance-0eeb2bd99ae07173be21a5fc86db7a2ea7fae0abdfb5e81350bf52f22a66ea80","transform":"Identity"},{"key":"balance-3fc748c8cad37d3c5b65d3cd53b189ec4f3da23475ce4d3dae02bc08e63b8329","transform":"Identity"},{"key":"balance-0eeb2bd99ae07173be21a5fc86db7a2ea7fae0abdfb5e81350bf52f22a66ea80","transform":{"WriteCLValue":{"cl_type":"U512","bytes":"0e001f0afa095bc138938d44c64d31","parsed":"999999999999999999999999900000000"}}},{"key":"balance-3fc748c8cad37d3c5b65d3cd53b189ec4f3da23475ce4d3dae02bc08e63b8329","transform":{"AddUInt512":"100000000"}},{"key":"hash-b8527fd6de4c547f7afef1427094846b68a8762e61cf118bb69ea7e78b9e82d4","transform":"Identity"},{"key":"hash-b8527fd6de4c547f7afef1427094846b68a8762e61cf118bb69ea7e78b9e82d4","transform":"Identity"},{"key":"hash-090f97f668d33884974255ba853c74fdd5fb187ba6e48c0ac652f00e81b2b67f","transform":"Identity"},{"key":"hash-b8527fd6de4c547f7afef1427094846b68a8762e61cf118bb69ea7e78b9e82d4","transform":"Identity"},{"key":"balance-0eeb2bd99ae07173be21a5fc86db7a2ea7fae0abdfb5e81350bf52f22a66ea80","transform":"Identity"},{"key":"balance-05f54a84872c75f7f05c8e8aaf9338ec848fa1a5b4f07202e371955c982f7f60","transform":"Identity"},{"key":"balance-0eeb2bd99ae07173be21a5fc86db7a2ea7fae0abdfb5e81350bf52f22a66ea80","transform":{"WriteCLValue":{"cl_type":"U512","bytes":"0e00260765095bc138938d44c64d31","parsed":"999999999999999999999997400000000"}}},{"key":"balance-05f54a84872c75f7f05c8e8aaf9338ec848fa1a5b4f07202e371955c982f7f60","transform":{"AddUInt512":"2500000000"}},{"key":"transfer-bae0cec10eb82aa81af18a31393ff5d5023e25ea7ed820e978b8407ccc22160d","transform":{"WriteTransfer":{"deploy_hash":"fb81219f33aa58a2c2f50f7eea20c3065963f61bc3c74810729f10dc21981087","from":"account-hash-59cbc880e6d1f7407f18c36393c33d47ae51d5a54258f94a837ff996bf25a34d","to":"account-hash-a6cdb6f049363f6ab119be0c961c36e4a3c09319589341dd861f405d9836fc67","source":"uref-0eeb2bd99ae07173be21a5fc86db7a2ea7fae0abdfb5e81350bf52f22a66ea80-007","target":"uref-05f54a84872c75f7f05c8e8aaf9338ec848fa1a5b4f07202e371955c982f7f60-004","amount":"2500000000","gas":"0","id":1}}},{"key":"deploy-fb81219f33aa58a2c2f50f7eea20c3065963f61bc3c74810729f10dc21981087","transform":{"WriteDeployInfo":{"deploy_hash":"fb81219f33aa58a2c2f50f7eea20c3065963f61bc3c74810729f10dc21981087","transfers":["transfer-bae0cec10eb82aa81af18a31393ff5d5023e25ea7ed820e978b8407ccc22160d"],"from":"account-hash-59cbc880e6d1f7407f18c36393c33d47ae51d5a54258f94a837ff996bf25a34d","source":"uref-0eeb2bd99ae07173be21a5fc86db7a2ea7fae0abdfb5e81350bf52f22a66ea80-007","gas":"100000000"}}},{"key":"hash-c5cbbfd90319b74de3e147e33c17d480ea782bafa37e2a08b7dda37d3713e036","transform":"Identity"},{"key":"hash-c5cbbfd90319b74de3e147e33c17d480ea782bafa37e2a08b7dda37d3713e036","transform":"Identity"},{"key":"hash-5ba9ce15ffc7429476de4e278d23362759e37cbdcafd1a8efb2f8bb475e8574e","transform":"Identity"},{"key":"hash-c5cbbfd90319b74de3e147e33c17d480ea782bafa37e2a08b7dda37d3713e036","transform":"Identity"},{"key":"balance-3fc748c8cad37d3c5b65d3cd53b189ec4f3da23475ce4d3dae02bc08e63b8329","transform":"Identity"},{"key":"hash-c5cbbfd90319b74de3e147e33c17d480ea782bafa37e2a08b7dda37d3713e036","transform":"Identity"},{"key":"hash-b8527fd6de4c547f7afef1427094846b68a8762e61cf118bb69ea7e78b9e82d4","transform":"Identity"},{"key":"hash-090f97f668d33884974255ba853c74fdd5fb187ba6e48c0ac652f00e81b2b67f","transform":"Identity"},{"key":"hash-b8527fd6de4c547f7afef1427094846b68a8762e61cf118bb69ea7e78b9e82d4","transform":"Identity"},{"key":"balance-3fc748c8cad37d3c5b65d3cd53b189ec4f3da23475ce4d3dae02bc08e63b8329","transform":"Identity"},{"key":"balance-8bd1ab925b4c91ea54b4aa6edadfd11d2be294cb64c59745258cb67e32aea67a","transform":"Identity"},{"key":"balance-3fc748c8cad37d3c5b65d3cd53b189ec4f3da23475ce4d3dae02bc08e63b8329","transform":{"WriteCLValue":{"cl_type":"U512","bytes":"00","parsed":"0"}}},{"key":"balance-8bd1ab925b4c91ea54b4aa6edadfd11d2be294cb64c59745258cb67e32aea67a","transform":{"AddUInt512":"100000000"}}]},"transfers":["transfer-bae0cec10eb82aa81af18a31393ff5d5023e25ea7ed820e978b8407ccc22160d"],"cost":"100000000"}}}}
	at com.casper.sdk.service.impl.event.EventBuilder.buildPojoEvent(EventBuilder.java:132)
	at com.casper.sdk.service.impl.event.EventBuilder.buildEvent(EventBuilder.java:106)
	at com.casper.sdk.service.impl.event.EventBuilderTest.getEvent(EventBuilderTest.java:232)
	at com.casper.sdk.service.impl.event.EventBuilderTest.buildDeployProcessedEvent(EventBuilderTest.java:159)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at  .... 
```

I have then merged your branch with 'issues/120-fix' and 'merging' branches and got this error:

```
Expected: is an instance of com.casper.sdk.model.event.deployaccepted.DeployAccepted
     but: <com.casper.sdk.model.event.deployprocessed.DeployProcessed@108ed58d> is a com.casper.sdk.model.event.deployprocessed.DeployProcessed
java.lang.AssertionError: 
Expected: is an instance of com.casper.sdk.model.event.deployaccepted.DeployAccepted
     but: <com.casper.sdk.model.event.deployprocessed.DeployProcessed@108ed58d> is a com.casper.sdk.model.event.deployprocessed.DeployProcessed
```

I've then made some corrections in the test like setting the expected class as DeployProcessed and in related POJO's, changing from String to Digest and it appears to be working, would you check it?

Final result:
```
-------------------------------------------------------------------
|  Results: SUCCESS (123 tests, 116 passed, 0 failed, 7 skipped)  |
-------------------------------------------------------------------
```

The branch with the merging and changes is at 'issues/146'.

Thanks!
