### ISSUE TITLE
Error while retrieving specific Deploy

### ISSUE THREAD

**Issue by indyMccarthy** [casper-network/casper-java-sdk#207]
Hi ! 👋

It seems that some deploys, at least the `2f430047c90597ef30467bb5393081e83a69c76ae215b1a89e01918748831a60` and `f8c3d8a9bc4b2a07928c9eeaa8bac41ec54b13cc767eb25509770b333f0f77e9` (WASM deploy), are not well handled by the JSON deserializer.
Tested with the release `2.3.3`

```java
DeployData deploy = casperService.getDeploy("2f430047c90597ef30467bb5393081e83a69c76ae215b1a89e01918748831a60");
```
returns the following exception:

```
java.lang.reflect.UndeclaredThrowableException
	at ProcessorTest.testDeployProcessor(ProcessorTest.java:20)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Index 0 out of bounds for length 0
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: com.casper.sdk.model.deploy.DeployData["execution_results"]->java.util.ArrayList[0]->com.casper.sdk.model.deploy.JsonExecutionResult["result"]->com.casper.sdk.model.deploy.executionresult.Success["effect"]->com.casper.sdk.model.deploy.ExecutionEffect["transforms"]->java.util.ArrayList[11]->com.casper.sdk.model.deploy.Entry["transform"]->com.casper.sdk.model.deploy.transform.WriteCLValue["WriteCLValue"]->com.casper.sdk.model.clvalue.CLValueList["bytes"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:276)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:630)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:618)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:143)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.casper.sdk.jackson.deserializer.AbstractAnyOfDeserializer.deserializeTypedFromObject(AbstractAnyOfDeserializer.java:61)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.casper.sdk.jackson.deserializer.AbstractAnyOfDeserializer.deserializeTypedFromObject(AbstractAnyOfDeserializer.java:61)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer._deserialize(AsWrapperTypeDeserializer.java:121)
	at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer.deserializeTypedFromObject(AsWrapperTypeDeserializer.java:52)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4801)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3043)
	at com.googlecode.jsonrpc4j.JsonRpcClient.constructResponseObject(JsonRpcClient.java:292)
	at com.googlecode.jsonrpc4j.JsonRpcClient.readResponse(JsonRpcClient.java:202)
	at com.googlecode.jsonrpc4j.JsonRpcClient.readResponse(JsonRpcClient.java:539)
	at com.googlecode.jsonrpc4j.JsonRpcHttpClient.invoke(JsonRpcHttpClient.java:143)
	at com.googlecode.jsonrpc4j.ProxyUtil$3.invoke(ProxyUtil.java:213)
	... 1 more
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.casper.sdk.model.clvalue.CLValueList.setChildTypes(CLValueList.java:103)
	at com.casper.sdk.model.clvalue.CLValueList.serialize(CLValueList.java:59)
	at com.casper.sdk.model.clvalue.serde.CasperSerializableObject.serialize(CasperSerializableObject.java:36)
	at com.casper.sdk.model.clvalue.AbstractCLValue.setValue(AbstractCLValue.java:54)
	at com.casper.sdk.model.clvalue.CLValueList.deserializeCustom(CLValueList.java:98)
	at com.casper.sdk.model.clvalue.AbstractCLValue.deserialize(AbstractCLValue.java:124)
	at com.casper.sdk.model.clvalue.AbstractCLValueWithChildren.setJsonBytes(AbstractCLValueWithChildren.java:53)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:141)
	... 42 more


Process finished with exit code -1
```

```java
DeployData deploy = casperService.getDeploy("f8c3d8a9bc4b2a07928c9eeaa8bac41ec54b13cc767eb25509770b333f0f77e9");
```
returns the following exception:
```
java.lang.reflect.UndeclaredThrowableException
	at ProcessorTest.testDeployProcessor(ProcessorTest.java:15)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: N/A
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: com.casper.sdk.model.deploy.DeployData["deploy"]->com.casper.sdk.model.deploy.Deploy["session"]->com.casper.sdk.model.deploy.executabledeploy.ModuleBytes["args"]->java.util.ArrayList[2]->com.casper.sdk.model.deploy.NamedArg["clValue"]->com.casper.sdk.model.clvalue.CLValueMap["bytes"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:276)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:630)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:618)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:143)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.casper.sdk.jackson.deserializer.AbstractAnyOfDeserializer.deserializeTypedFromObject(AbstractAnyOfDeserializer.java:61)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:138)
	at com.fasterxml.jackson.databind.deser.impl.BeanAsArrayDeserializer.deserialize(BeanAsArrayDeserializer.java:127)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer._deserialize(AsWrapperTypeDeserializer.java:121)
	at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer.deserializeTypedFromObject(AsWrapperTypeDeserializer.java:52)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4801)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3043)
	at com.googlecode.jsonrpc4j.JsonRpcClient.constructResponseObject(JsonRpcClient.java:292)
	at com.googlecode.jsonrpc4j.JsonRpcClient.readResponse(JsonRpcClient.java:202)
	at com.googlecode.jsonrpc4j.JsonRpcClient.readResponse(JsonRpcClient.java:539)
	at com.googlecode.jsonrpc4j.JsonRpcHttpClient.invoke(JsonRpcHttpClient.java:143)
	at com.googlecode.jsonrpc4j.ProxyUtil$3.invoke(ProxyUtil.java:213)
	... 1 more
Caused by: java.util.NoSuchElementException
	at com.casper.sdk.model.clvalue.CLValueMap.setChildTypes(CLValueMap.java:116)
	at com.casper.sdk.model.clvalue.CLValueMap.serialize(CLValueMap.java:60)
	at com.casper.sdk.model.clvalue.serde.CasperSerializableObject.serialize(CasperSerializableObject.java:36)
	at com.casper.sdk.model.clvalue.AbstractCLValue.setValue(AbstractCLValue.java:54)
	at com.casper.sdk.model.clvalue.CLValueMap.deserializeCustom(CLValueMap.java:110)
	at com.casper.sdk.model.clvalue.AbstractCLValue.deserialize(AbstractCLValue.java:124)
	at com.casper.sdk.model.clvalue.AbstractCLValueWithChildren.setJsonBytes(AbstractCLValueWithChildren.java:53)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:141)
	... 30 more


Process finished with exit code -1
```

**Comment by meywood** [comment]
@indyMccarthy can you please retry with V2.4.0 V2.3.3 was released in error.

**Comment by indyMccarthy** [comment]
I tested again, with the `V2.4.0` this time, and got the exact same exception.

**Comment by stormeye2000** [comment]
Hi @indyMccarthy 
Please try v2.4.1, this should fix your issue
Thanks

**Comment by cnorburn** [comment]
Hi @indyMccarthy
Please try v2.4.1, this should fix your issue
Thanks
